// src/svelte/components/MidiBadge.svelte
<script lang="ts">
  import { midiTargetBadge } from 'dialkit/midi';
  import type { MidiController, MidiControllerSnapshot, MidiBadgeState, MidiMappingOwner } from 'dialkit/midi';

  let { controller, panelId, path, ownerToken } = $props<{
    controller: MidiController;
    panelId: string;
    path: string;
    ownerToken?: MidiMappingOwner;
  }>();

  let snapshot = $state<MidiControllerSnapshot>(controller.getSnapshot());

  $effect(() => {
    snapshot = controller.getSnapshot();
    const unsub = controller.subscribe(() => {
      snapshot = controller.getSnapshot();
    });
    return unsub;
  });

  const badge = $derived(
    controller.canMapTarget(panelId, path)
      ? midiTargetBadge(snapshot, panelId, path)
      : null
  );

  const badgeText = (state: MidiBadgeState, cc: number | null): string => {
    switch (state) {
      case 'select': return 'Map';
      case 'listening': return 'Move control';
      case 'warning': return 'Use MIDI CC';
      case 'bound': return '';
    }
  };

  const badgeTitle: Record<MidiBadgeState, string> = {
    select: 'Map this control to MIDI',
    listening: 'Move the hardware control you want to assign — Esc to cancel',
    warning: 'Use a compatible hardware control that sends MIDI CC',
    bound: 'MIDI mapped — click to re-map',
  };

  const stop = (e: Event) => e.stopPropagation();

  const handleClick = (e: MouseEvent) => {
    e.stopPropagation();
    if (!badge) return;
    if (badge.state === 'listening') {
      controller.cancelLearn();
      return;
    }
    if (badge.state === 'bound' && (!controller.getSnapshot().mapping || ownerToken)) {
      controller.startMapping(undefined, ownerToken);
    }
    const inputId = controller.getSnapshot().activeInputId ?? undefined;
    controller.learn({ panelId, path }, { inputId }).catch(() => undefined);
  };
</script>

{#if badge}
  <button
    type="button"
    class="dialkit-midi-pill"
    data-state={badge.state}
    data-active={String(badge.state === 'bound' && snapshot.status === 'connected' && (() => {
      const binding = controller.getBindingForTarget(panelId, path);
      return binding?.inputId
        ? snapshot.inputs.some((input) => input.id === binding.inputId)
        : snapshot.inputs.length > 0;
    })())}
    title={badgeTitle[badge.state]}
    aria-label={badgeTitle[badge.state]}
    onpointerdown={stop}
    onmousedown={stop}
    onclick={handleClick}
  >
    {#if badge.state === 'bound'}
      <span class="dialkit-midi-live-dot"></span>
    {:else}
      {badgeText(badge.state, badge.cc)}
    {/if}
  </button>
{/if}

// src/solid/components/MidiBadge.tsx
import { Show } from 'solid-js';
import { midiTargetBadge } from '../../midi';
import type { MidiBadgeState, MidiController, MidiControllerSnapshot, MidiMappingOwner } from '../../midi';

interface MidiBadgeProps {
  controller: MidiController;
  panelId: string;
  path: string;
  /** Current controller snapshot, or null when no controller is active. */
  snapshot: MidiControllerSnapshot | null;
  ownerToken?: MidiMappingOwner;
}

const badgeText = (state: MidiBadgeState, cc: number | null): string =>
  state === 'select' ? 'Map' : state === 'listening' ? 'Move control' : state === 'warning' ? 'Use MIDI CC' : '';

const badgeTitle: Record<MidiBadgeState, string> = {
  select: 'Map this control to MIDI',
  listening: 'Move the hardware control you want to assign — Esc to cancel',
  warning: 'Use a compatible hardware control that sends MIDI CC',
  bound: 'MIDI mapped — click to re-map',
};

/**
 * The MIDI mapping badge shown on a numeric control. Derived from the shared
 * `midiTargetBadge` view helper so every framework adapter stays identical.
 * Renders nothing when no badge applies.
 */
export function MidiBadge(props: MidiBadgeProps) {
  const badge = () => {
    const snapshot = props.snapshot;
    return snapshot ? midiTargetBadge(snapshot, props.panelId, props.path) : null;
  };

  const stop = (e: Event) => e.stopPropagation();
  const onClick = (e: MouseEvent) => {
    e.stopPropagation();
    const current = badge();
    if (!current) return;
    if (current.state === 'listening') {
      props.controller.cancelLearn();
      return;
    }
    if (current.state === 'bound' && (!props.controller.getSnapshot().mapping || props.ownerToken)) {
      props.controller.startMapping(undefined, props.ownerToken);
    }
    const inputId = props.controller.getSnapshot().activeInputId ?? undefined;
    props.controller.learn({ panelId: props.panelId, path: props.path }, { inputId }).catch(() => undefined);
  };

  return (
    <Show when={badge()}>
      {(current) => (
        <button
          type="button"
          class="dialkit-midi-pill"
          data-state={current().state}
          data-active={String(current().state === 'bound' && (() => {
            const snap = props.snapshot;
            const binding = props.controller.getBindingForTarget(props.panelId, props.path);
            if (!snap || snap.status !== 'connected') return false;
            return binding?.inputId
              ? snap.inputs.some((input) => input.id === binding.inputId)
              : snap.inputs.length > 0;
          })())}
          title={badgeTitle[current().state]}
          aria-label={badgeTitle[current().state]}
          onPointerDown={stop}
          onMouseDown={stop}
          onClick={onClick}
        >
          <Show when={current().state !== 'bound'} fallback={<span class="dialkit-midi-live-dot" />}>
            {badgeText(current().state, current().cc)}
          </Show>
        </button>
      )}
    </Show>
  );
}
