// src/components/Toggle.tsx
import { SegmentedControl } from './SegmentedControl';
import type { ShortcutConfig } from '../store/DialStore';
import { formatToggleShortcut } from '../shortcut-utils';
import type { ReactNode } from 'react';

interface ToggleProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  shortcut?: ShortcutConfig;
  shortcutActive?: boolean;
  midiSlot?: ReactNode;
}

export function Toggle({ label, checked, onChange, shortcut, shortcutActive, midiSlot }: ToggleProps) {
  return (
    <div className="dialkit-labeled-control">
      <span className="dialkit-labeled-control-label">
        {label}
        {shortcut && (
          <span className={`dialkit-shortcut-pill${shortcutActive ? ' dialkit-shortcut-pill-active' : ''}`}>
            {formatToggleShortcut(shortcut)}
          </span>
        )}
        {midiSlot}
      </span>
      <SegmentedControl
        options={[
          { value: 'off' as const, label: 'Off' },
          { value: 'on' as const, label: 'On' },
        ]}
        value={checked ? 'on' : 'off'}
        onChange={(val) => onChange(val === 'on')}
      />
    </div>
  );
}

// src/solid/components/Toggle.tsx
import { Show, type JSX } from 'solid-js';
import { SegmentedControl } from './SegmentedControl';
import type { ShortcutConfig } from '../../store/DialStore';
import { formatToggleShortcut } from '../../shortcut-utils';

interface ToggleProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  shortcut?: ShortcutConfig;
  shortcutActive?: boolean;
  midiSlot?: JSX.Element;
}

export function Toggle(props: ToggleProps) {
  return (
    <div class="dialkit-labeled-control">
      <span class="dialkit-labeled-control-label">
        {props.label}
        <Show when={props.shortcut}>
          <span class={`dialkit-shortcut-pill${props.shortcutActive ? ' dialkit-shortcut-pill-active' : ''}`}>
            {formatToggleShortcut(props.shortcut!)}
          </span>
        </Show>
        {props.midiSlot}
      </span>
      <SegmentedControl
        options={[
          { value: 'off' as const, label: 'Off' },
          { value: 'on' as const, label: 'On' },
        ]}
        value={props.checked ? 'on' : 'off'}
        onChange={(val) => props.onChange(val === 'on')}
      />
    </div>
  );
}
