// src/solid/components/ShortcutsMenu.tsx
import { createSignal, createEffect, onCleanup, For } from 'solid-js';
import { Portal } from 'solid-js/web';
import { animate } from 'motion';
import { useFloatingDropdown } from '../floating';
import { DialStore, ShortcutConfig } from '../../store/DialStore';

interface ShortcutsMenuProps {
  panelId: string;
}

function formatShortcutKey(sc: ShortcutConfig): string {
  if (!sc.key) return '\u2014';
  const mod = sc.modifier === 'alt' ? '\u2325'
    : sc.modifier === 'shift' ? '\u21E7'
    : sc.modifier === 'meta' ? '\u2318'
    : '';
  return `${mod}${sc.key.toUpperCase()}`;
}

function formatInteraction(sc: ShortcutConfig): string {
  const interaction = sc.interaction ?? 'scroll';
  switch (interaction) {
    case 'scroll': return sc.key ? 'key+scroll' : 'scroll';
    case 'drag': return 'key+drag';
    case 'move': return 'key+move';
    case 'scroll-only': return 'scroll';
  }
}

export function ShortcutsMenu(props: ShortcutsMenuProps) {
  const [isOpen, setIsOpen] = createSignal(false);

  let triggerRef!: HTMLButtonElement;
  let dropdownRef: HTMLDivElement | undefined;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let triggerTapAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let dropdownEnterAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let dropdownExitAnim: any = null;

  const tapTransition = { type: 'spring' as const, visualDuration: 0.15, bounce: 0.3 };

  const open = () => setIsOpen(true);

  const close = () => setIsOpen(false);

  // Floating UI positioning while open.
  useFloatingDropdown(
    isOpen,
    () => triggerRef,
    () => dropdownRef,
    { placement: 'bottom-end' }
  );

  const toggle = () => {
    if (isOpen()) close();
    else open();
  };

  // Close on mousedown outside
  createEffect(() => {
    if (!isOpen()) return;

    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      if (triggerRef?.contains(target) || dropdownRef?.contains(target)) return;
      close();
    };

    document.addEventListener('mousedown', handler);
    onCleanup(() => document.removeEventListener('mousedown', handler));
  });

  // Animate dropdown enter/exit
  createEffect(() => {
    const opened = isOpen();
    if (!dropdownRef) return;

    if (opened) {
      dropdownExitAnim?.stop();
      dropdownRef.style.pointerEvents = 'auto';
      dropdownEnterAnim = animate(
        dropdownRef,
        { opacity: 1, y: 0, scale: 1 },
        { type: 'spring', visualDuration: 0.15, bounce: 0 }
      );
    } else {
      dropdownEnterAnim?.stop();
      dropdownRef.style.pointerEvents = 'none';
      dropdownExitAnim = animate(
        dropdownRef,
        { opacity: 0, y: 4, scale: 0.97 },
        { type: 'spring', visualDuration: 0.15, bounce: 0 }
      );
    }
  });

  onCleanup(() => {
    triggerTapAnim?.stop();
    dropdownEnterAnim?.stop();
    dropdownExitAnim?.stop();
  });

  const panel = () => DialStore.getPanel(props.panelId);

  const rows = () => {
    const p = panel();
    if (!p) return [];
    const shortcuts = Object.entries(p.shortcuts);
    if (shortcuts.length === 0) return [];

    return shortcuts.map(([path, shortcut]) => {
      const findLabel = (controls: typeof p.controls): string => {
        for (const c of controls) {
          if (c.path === path) return c.label;
          if (c.type === 'folder' && c.children) {
            const found = findLabel(c.children);
            if (found) return found;
          }
        }
        return path;
      };
      return {
        path,
        shortcut,
        label: findLabel(p.controls),
      };
    });
  };

  return (
    <>
      <button
        ref={triggerRef}
        class="dialkit-shortcuts-trigger"
        onClick={toggle}
        onPointerDown={() => {
          triggerTapAnim?.stop();
          triggerTapAnim = animate(triggerRef, { scale: 0.9 }, tapTransition);
        }}
        onPointerUp={() => {
          triggerTapAnim?.stop();
          triggerTapAnim = animate(triggerRef, { scale: 1 }, tapTransition);
        }}
        onPointerCancel={() => {
          triggerTapAnim?.stop();
          triggerTapAnim = animate(triggerRef, { scale: 1 }, tapTransition);
        }}
        onPointerLeave={() => {
          triggerTapAnim?.stop();
          triggerTapAnim = animate(triggerRef, { scale: 1 }, tapTransition);
        }}
        title="Keyboard shortcuts"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <rect x="2" y="6" width="20" height="12" rx="2" />
          <path d="M6 10H6.01" />
          <path d="M10 10H10.01" />
          <path d="M14 10H14.01" />
          <path d="M18 10H18.01" />
          <path d="M8 14H16" />
        </svg>
      </button>

      <Portal mount={document.body}>
        <div
          ref={(el) => {
            dropdownRef = el;
            // Initialize hidden
            el.style.opacity = '0';
            el.style.transform = 'translateY(4px) scale(0.97)';
            el.style.pointerEvents = 'none';
          }}
          class="dialkit-root dialkit-shortcuts-dropdown"
          style={{ position: 'fixed', top: '0', left: '0' }}
        >
          <div class="dialkit-shortcuts-title">Keyboard Shortcuts</div>
          <div class="dialkit-shortcuts-list">
            <For each={rows()}>
              {(row) => (
                <div class="dialkit-shortcuts-row">
                  <span class="dialkit-shortcuts-row-key">
                    {formatShortcutKey(row.shortcut)}
                  </span>
                  <span class="dialkit-shortcuts-row-label">{row.label}</span>
                  <span class="dialkit-shortcuts-row-mode">{formatInteraction(row.shortcut)}</span>
                </div>
              )}
            </For>
          </div>
          <div class="dialkit-shortcuts-hint">See pill badges on controls for keys</div>
        </div>
      </Portal>
    </>
  );
}

// src/components/ShortcutsMenu.tsx
import { useState, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'motion/react';
import { DialStore, ShortcutConfig } from '../store/DialStore';
import { useFloatingDropdown } from '../hooks/useFloatingDropdown';

interface ShortcutsMenuProps {
  panelId: string;
}

function formatShortcutKey(sc: ShortcutConfig): string {
  if (!sc.key) return '—';
  const mod = sc.modifier === 'alt' ? '⌥'
    : sc.modifier === 'shift' ? '⇧'
    : sc.modifier === 'meta' ? '⌘'
    : '';
  return `${mod}${sc.key.toUpperCase()}`;
}

function formatInteraction(sc: ShortcutConfig): string {
  const interaction = sc.interaction ?? 'scroll';
  switch (interaction) {
    case 'scroll': return sc.key ? 'key+scroll' : 'scroll';
    case 'drag': return 'key+drag';
    case 'move': return 'key+move';
    case 'scroll-only': return 'scroll';
  }
}

export function ShortcutsMenu({ panelId }: ShortcutsMenuProps) {
  const [isOpen, setIsOpen] = useState(false);
  const { triggerRef, floatingRef } = useFloatingDropdown<HTMLButtonElement, HTMLDivElement>(isOpen, {
    placement: 'bottom-end',
  });

  const open = useCallback(() => {
    setIsOpen(true);
  }, []);

  const close = useCallback(() => setIsOpen(false), []);

  const toggle = useCallback(() => {
    if (isOpen) close();
    else open();
  }, [isOpen, open, close]);

  // Close on mousedown outside
  useEffect(() => {
    if (!isOpen) return;

    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      if (
        triggerRef.current?.contains(target) ||
        floatingRef.current?.contains(target)
      ) return;
      close();
    };

    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [isOpen, close]);

  const panel = DialStore.getPanel(panelId);
  if (!panel) return null;

  const shortcuts = Object.entries(panel.shortcuts);
  if (shortcuts.length === 0) return null;

  // Build shortcut rows with labels from controls
  const rows = shortcuts.map(([path, shortcut]) => {
    // Find control label
    const findLabel = (controls: typeof panel.controls): string => {
      for (const c of controls) {
        if (c.path === path) return c.label;
        if (c.type === 'folder' && c.children) {
          const found = findLabel(c.children);
          if (found) return found;
        }
      }
      return path;
    };
    return {
      path,
      shortcut,
      label: findLabel(panel.controls),
    };
  });

  return (
    <>
      <motion.button
        ref={triggerRef}
        className="dialkit-shortcuts-trigger"
        onClick={toggle}
        title="Keyboard shortcuts"
        whileTap={{ scale: 0.9 }}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <rect x="2" y="6" width="20" height="12" rx="2" />
          <path d="M6 10H6.01" />
          <path d="M10 10H10.01" />
          <path d="M14 10H14.01" />
          <path d="M18 10H18.01" />
          <path d="M8 14H16" />
        </svg>
      </motion.button>

      {createPortal(
        <AnimatePresence>
          {isOpen && (
            <motion.div
              ref={floatingRef}
              className="dialkit-root dialkit-shortcuts-dropdown"
              style={{ position: 'fixed', top: 0, left: 0 }}
              initial={{ opacity: 0, y: 4, scale: 0.97 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: 4, scale: 0.97, pointerEvents: 'none' as any }}
              transition={{ type: 'spring', visualDuration: 0.15, bounce: 0 }}
            >
              <div className="dialkit-shortcuts-title">Keyboard Shortcuts</div>
              <div className="dialkit-shortcuts-list">
                {rows.map((row) => (
                  <div key={row.path} className="dialkit-shortcuts-row">
                    <span className="dialkit-shortcuts-row-key">
                      {formatShortcutKey(row.shortcut)}
                    </span>
                    <span className="dialkit-shortcuts-row-label">{row.label}</span>
                    <span className="dialkit-shortcuts-row-mode">{formatInteraction(row.shortcut)}</span>
                  </div>
                ))}
              </div>
              <div className="dialkit-shortcuts-hint">See pill badges on controls for keys</div>
            </motion.div>
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  );
}
