// src/svelte/components/Toggle.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import SegmentedControl from './SegmentedControl.svelte';
  import type { ShortcutConfig } from 'dialkit/store';
  import { formatToggleShortcut } from '../../shortcut-utils';

  let { label, checked, onChange, shortcut, shortcutActive = false, midiSlot } = $props<{
    label: string;
    checked: boolean;
    onChange: (checked: boolean) => void;
    shortcut?: ShortcutConfig;
    shortcutActive?: boolean;
    midiSlot?: Snippet;
  }>();
</script>

<div class="dialkit-labeled-control">
  <span class="dialkit-labeled-control-label">
    {label}
    {#if shortcut}
      <span class={`dialkit-shortcut-pill${shortcutActive ? ' dialkit-shortcut-pill-active' : ''}`}>
        {formatToggleShortcut(shortcut)}
      </span>
    {/if}
    {#if midiSlot}{@render midiSlot()}{/if}
  </span>
  <SegmentedControl
    options={[
      { value: 'off', label: 'Off' },
      { value: 'on', label: 'On' },
    ]}
    value={checked ? 'on' : 'off'}
    onChange={(val) => onChange(val === 'on')}
  />
</div>

// src/components/Toggle.tsx
import { SegmentedControl } from './SegmentedControl';
import type { ShortcutConfig } from '../store/DialStore';
import { formatToggleShortcut } from '../shortcut-utils';
import type { ReactNode } from 'react';

interface ToggleProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  shortcut?: ShortcutConfig;
  shortcutActive?: boolean;
  midiSlot?: ReactNode;
}

export function Toggle({ label, checked, onChange, shortcut, shortcutActive, midiSlot }: ToggleProps) {
  return (
    <div className="dialkit-labeled-control">
      <span className="dialkit-labeled-control-label">
        {label}
        {shortcut && (
          <span className={`dialkit-shortcut-pill${shortcutActive ? ' dialkit-shortcut-pill-active' : ''}`}>
            {formatToggleShortcut(shortcut)}
          </span>
        )}
        {midiSlot}
      </span>
      <SegmentedControl
        options={[
          { value: 'off' as const, label: 'Off' },
          { value: 'on' as const, label: 'On' },
        ]}
        value={checked ? 'on' : 'off'}
        onChange={(val) => onChange(val === 'on')}
      />
    </div>
  );
}
